PRODUCT_VERSION_MAJOR = 16
PRODUCT_VERSION_MINOR = 0

ifeq ($(WITH_GMS),true)
CUSTOM_EDITION := GAPPS
else
CUSTOM_EDITION := VANILLA
endif

# Increase CR Version with each major release.
CR_VERSION := 12.12

CUSTOM_BUILD_DATETIME := $(shell date +%s)
CUSTOM_BUILD_DATE := $(shell date -d @$(CUSTOM_BUILD_DATETIME) +"%Y%m%d-%H%M%S")

# Internal version
LINEAGE_VERSION := AresOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CUSTOM_EDITION)-$(LINEAGE_BUILD)-$(CUSTOM_BUILD_DATE)

# Display version
LINEAGE_DISPLAY_VERSION := v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CUSTOM_EDITION)-$(CUSTOM_BUILD_DATE)

# LineageOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.crdroid.build.version=$(CR_VERSION) \
    ro.crdroid.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.crdroid.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.ares.version=$(LINEAGE_VERSION)
